/**
 * Enhanced Playwright test fixtures.
 *
 * Drop-in replacement for `@playwright/test`:
 *   import { test, expect } from './fixtures';
 *
 * Added fixtures
 * ──────────────
 * • `step(title, fn)` — wraps `test.step()` and auto-captures a screenshot at
 *   the end of the step.  The screenshot is attached to the test result and
 *   appears in both the HTML report and the per-test STEPS.md generated by
 *   `reporter/markdown.reporter.ts`.
 *
 *   Usage:
 *     test('my flow', async ({ page, step }) => {
 *       await step('Navigate to login', async () => {
 *         await page.goto('/auth/login');
 *       });
 *     });
 *
 * Built-in Playwright settings (`playwright.config.ts`) handle:
 *   • `screenshot: 'on'`  — final state screenshot after every test
 *   • `video: 'on'`       — full video recording of every test run
 */

import { test as base, expect } from '@playwright/test';
import type { Page, APIRequestContext, BrowserContext } from '@playwright/test';

// Re-export standard Playwright types so callers need no extra imports.
export { expect };
export type { Page, APIRequestContext, BrowserContext };

type StepFn = (title: string, fn: () => Promise<void>) => Promise<void>;

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
}

export const test = base.extend<{ step: StepFn }>({
  page: async ({ page }, use, testInfo) => {
    let navigationCount = 0;

    const attachNavigationScreenshot = async (action: string) => {
      const currentUrl = page.url();
      if (!currentUrl || currentUrl === 'about:blank') {
        return;
      }

      navigationCount += 1;
      const screenshotPath = testInfo.outputPath(
        `navigation-${String(navigationCount).padStart(2, '0')}-${slugify(action)}.png`,
      );

      await page.screenshot({ path: screenshotPath, fullPage: false }).catch(() => {});
      await testInfo
        .attach(`Navigation ${navigationCount}: ${action}`, {
          path: screenshotPath,
          contentType: 'image/png',
        })
        .catch(() => {});
    };

    const originalGoto = page.goto.bind(page);
    const originalReload = page.reload.bind(page);
    const originalGoBack = page.goBack.bind(page);
    const originalGoForward = page.goForward.bind(page);

    (page as Page & { goto: typeof page.goto }).goto = (async (...args) => {
      const response = await originalGoto(...args);
      const target = typeof args[0] === 'string' ? args[0] : page.url();
      await attachNavigationScreenshot(`goto ${target}`);
      return response;
    }) as typeof page.goto;

    (page as Page & { reload: typeof page.reload }).reload = (async (...args) => {
      const response = await originalReload(...args);
      await attachNavigationScreenshot(`reload ${page.url()}`);
      return response;
    }) as typeof page.reload;

    (page as Page & { goBack: typeof page.goBack }).goBack = (async (...args) => {
      const response = await originalGoBack(...args);
      if (response) {
        await attachNavigationScreenshot(`back ${page.url()}`);
      }
      return response;
    }) as typeof page.goBack;

    (page as Page & { goForward: typeof page.goForward }).goForward = (async (...args) => {
      const response = await originalGoForward(...args);
      if (response) {
        await attachNavigationScreenshot(`forward ${page.url()}`);
      }
      return response;
    }) as typeof page.goForward;

    await use(page);
  },

  /**
   * `step` fixture — call `await step('title', async () => { ... })` inside a
   * test to group actions, capture a labelled screenshot, and have both appear
   * in the generated STEPS.md.
   */
  step: async ({ page }, use, testInfo) => {
    let stepCount = 0;

    await use(async (title: string, fn: () => Promise<void>) => {
      stepCount++;
      const slug = slugify(title);
      const screenshotPath = testInfo.outputPath(
        `step-${String(stepCount).padStart(2, '0')}-${slug}.png`,
      );

      // test.step records the step in the result so the reporter can document it.
      await base.step(title, async () => {
        await fn();
        // Screenshot captured AFTER step body completes — no navigation race.
        await page.screenshot({ path: screenshotPath, fullPage: false }).catch(() => {});
        await testInfo
          .attach(`Step ${stepCount}: ${title}`, {
            path: screenshotPath,
            contentType: 'image/png',
          })
          .catch(() => {});
      });
    });
  },
});
